project:
  type: website
  output-dir: docs
  resources: [CNAME]

website:
  title: "Emergent Intelligence"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        menu:
        - text: "Immune System"
          href: projects/immune_system/index.qmd
        - text: "Ants"
          href: projects/ants/index.qmd
        - text: "Cellular Automata"
          href: projects/cellular_automata/index.qmd
        - text: "Spiking Neural Networks"
          href: projects/spiking_neural_networks/index.qmd

    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



