---
title: "Brian"
date: "2026-06-13"
description: ""
categories: [Spiking Neural Networks, Brian]
---

I will begin learning about spiking neural networks with the [Brian](https://briansimulator.org/) toolbox. Yes thats right. Brian. Not Brain. Very funny.

The reason I want to start with this one is because it seems to have a lot of features for modeling individual neurons. Before making networks of them, it would be great if I built up my understanding of the individual elements. 

The Brian team have very kindly put together a set of [examples and tutorials](https://brian2.readthedocs.io/en/stable/resources/tutorials/1-intro-to-brian-neurons.html) on the website, so I figured what better place to start than there. What you will find below is me walking through those examples and commenting on it as I go. I am not copy pasting everything from their examples, so if you want to see all the details I recommend visiting their examples page directly. 

### Introduction to Brian Part 1: Neurons


## Units

In brain, we can attach units to our quantities by multiplying them by the unit name. For example,
```
1000*amp
1e6*volt
1000*namp
```
Thats pretty cool. Even more cool is the fact that these units now effect all downstream operations. So you can do things like 
```
10*nA*5*Mohm
```
to get an output in units of Volts! If you try to combine units in a way that doesn't make sense (like adding volts to amps) it will result in an error. 

## Simple Model

The spiking model of a neuron is temporal. This means that we must be able to model its output as a function of time. In Brian, this is done using differential equations.
```
tau = 10*ms
eqs = '''
dv/dt = (1-v)/tau : 1
'''
```
In this example, `tau` represents our time step and `eqs` represents the differential equation used for modeling the neuron. The information to the right of the `:` symbol specifies the units of the variable that is defined by that differential equation (in this case v). When you see `1`, that means unitless. Note that in this differential equation, we must include the division by tau. The left side of the equation `dv/dt` has units of `1/seconds` so the right side must match. 

We can use this setup to create a neuron as follows
```
G = NeuronGroup(1,eqs)
```
As is indicated by the name, you can only create 'groups' of neurons in Brian. The two arguments here are the number of neurons in the group (in this case `1`) and the defining differential equations.

To simulate the neuron, we can now simply call the `run` command
```
run(100*ms)
```
